# fly.toml app configuration file generated for laybabylay-staging on 2026-06-16T01:20:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laybabylay-staging'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
